services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
        # condition: service_healthy
    volumes:
      - ./app:/code                 # <-- tu proyecto local en ./app queda en /code
    env_file:
    - .env.local
    ports:
      - "8010:8000"                 # host 8010 -> container 8000

volumes:
  mariadb_data:
