services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/code
    ports:
      - "8010:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_pass
      - DB_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django_db
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=django_pass

volumes:
  mariadb_data: