# Generated by Django 5.2.4 on 2025-07-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instance_instance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='instance_id',
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
