# Generated by Django 5.2.4 on 2025-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_instance_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
