# Generated by Django 5.2.4 on 2025-07-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instance_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesend',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagesend',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagesend',
            name='send_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', help_text='Tipo de mensaje a enviar', max_length=5),
        ),
    ]
