# Generated by Django 5.2.4 on 2025-07-14 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_messagesend_filename_messagesend_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesend',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='messagesend',
            name='delay_max',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='messagesend',
            name='delay_min',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
