# Generated by Django 5.2.4 on 2025-07-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_messagesend_image_file_alter_messagesend_delay_max_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageSend',
            new_name='MessageCampaign',
        ),
        migrations.RenameField(
            model_name='messagehistory',
            old_name='send',
            new_name='campaign',
        ),
    ]
