# Generated by Django 5.2.4 on 2025-07-16 17:39

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_messagesend_to_messagecampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagecampaign',
            name='image_file',
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[core.utils.validate_supported_media_file]),
        ),
        migrations.AlterField(
            model_name='messagecampaign',
            name='send_type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media')], default='text', help_text='Tipo de mensaje a enviar', max_length=5),
        ),
    ]
