# Generated by Django 5.2.4 on 2025-07-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_messagecampaign_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecampaign',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
