# Generated by Django 5.2.4 on 2025-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_messagecampaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecampaign',
            name='status',
            field=models.CharField(choices=[('unsent', 'No enviada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('error', 'Con error')], default='unsent', max_length=10),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagecampaign',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
