# Generated by Django 5.2.4 on 2025-07-19 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_messagecampaign_status_messagecampaign_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contactgroup'),
        ),
        migrations.AlterField(
            model_name='messagecampaign',
            name='status',
            field=models.CharField(choices=[('unsent', 'Unsent'), ('sending', 'Sending'), ('sent', 'Sent'), ('error', 'Failed')], default='unsent', max_length=10),
        ),
    ]
