# Generated by Django 5.2.4 on 2025-07-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecampaign',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
